### ISSUE TITLE
添加Neumann边界条件后报错

### ISSUE THREAD

**Issue by WangHanwei1996** [PaddlePaddle/PaddleScience#219]
根据LDC算例改的管道流动在设定Neumann边界条件时报错
```
# set bounday condition
weight_down_u = lambda x, y: 1.0 - 10.0 * abs(x)
bc_top_u = psci.bc.Neumann('u')
bc_top_v = psci.bc.Neumann('v')
bc_top_p = psci.bc.Dirichlet('p', rhs=0)
bc_down_u = psci.bc.Dirichlet('u', rhs=0.0)
bc_down_v = psci.bc.Dirichlet('v', rhs=1.0, weight=weight_down_u)
bc_left_u = psci.bc.Dirichlet('u', rhs=0.0)
bc_left_v = psci.bc.Dirichlet('v', rhs=0.0)
bc_right_u = psci.bc.Dirichlet('u', rhs=0.0)
bc_right_v = psci.bc.Dirichlet('v', rhs=0.0)

#add bounday condition
pde.add_bc("top", bc_top_u, bc_top_v, bc_top_p)
pde.add_bc("down", bc_down_u, bc_down_v)
pde.add_bc("left", bc_left_u, bc_left_v)
pde.add_bc("right", bc_right_u, bc_right_v)

```
Dynamic Graph is Currently in Use.
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, imp, stat
Traceback (most recent call last):
  File "/home/dell/PaddleScience/dell-2.4.1/projects/tube(boundary)/ldc2d_steady_train.py", line 116, in <module>
    solution = solver.solve(num_epoch=epochs)
  File "/home/dell/PaddleScience/dell-2.4.1/projects/tube(boundary)/paddlescience/solver/solver.py", line 123, in solve
    return self.__solve_dynamic(num_epoch, bs, checkpoint_freq,
  File "/home/dell/PaddleScience/dell-2.4.1/projects/tube(boundary)/paddlescience/solver/solver.py", line 219, in __solve_dynamic
    loss, outs, loss_details = self.algo.compute(
  File "/home/dell/PaddleScience/dell-2.4.1/projects/tube(boundary)/paddlescience/algorithm/algorithm_pinns.py", line 596, in compute
    loss_b, out_b = self.loss.bc_loss(
  File "/home/dell/PaddleScience/dell-2.4.1/projects/tube(boundary)/paddlescience/loss/loss_L2.py", line 142, in bc_loss
    rst = cmploss.compute_formula(formula, input, input_attr, labels,
  File "/home/dell/PaddleScience/dell-2.4.1/projects/tube(boundary)/paddlescience/loss/loss_base.py", line 88, in compute_formula
    rst += self.__compute_formula_item(formula, input, input_attr,
  File "/home/dell/PaddleScience/dell-2.4.1/projects/tube(boundary)/paddlescience/loss/loss_base.py", line 121, in __compute_formula_item
    rst = rst * self.__compute_formula_der(item, input, normal, params)
  File "/home/dell/PaddleScience/dell-2.4.1/projects/tube(boundary)/paddlescience/loss/loss_base.py", line 180, in __compute_formula_der
    if normal.ndim == 1:
AttributeError: 'NoneType' object has no attribute 'ndim'

**Comment by Beschutzer** [comment]
![image](https://user-images.githubusercontent.com/90365464/220060774-fad9ac2d-85e0-499d-81b1-f21b9f04f59d.png)

**Comment by Beschutzer** [comment]
![image](https://user-images.githubusercontent.com/90365464/220061007-57f85707-b9fc-4803-9ebc-bceeab8e193a.png)

**Comment by HydrogenSulfate** [comment]
感谢反馈，该问题是已知BUG，会在近期尽快修复

**Comment by HydrogenSulfate** [comment]
你好，PaddleScience 1.0 正式版已经发布，提供了全新设计的 API 供开发使用，可以参考用户文档进行开发
https://paddlescience-docs.readthedocs.io/zh/latest/
