### ISSUE TITLE
Out of memory error on GPU0

### ISSUE THREAD

**Issue by jiangzhangze** [PaddlePaddle/PaddleScience#381]
### 请提出你的问题 Please ask your question

在运行cylinder_2D_steady算例的时候，报错GPU内存不足，以下是完整信息:
```
W0616 15:50:39.975569  9396 gpu_resources.cc:96] The GPU architecture in your current machine is Pascal, which is not compatible with Paddle installation with arch: 70 75 80 86 , it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
W0616 15:50:39.975569  9396 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 12.1, Runtime API Version: 11.7
W0616 15:50:39.978561  9396 gpu_resources.cc:149] device: 0, cuDNN Version: 8.4.
[2023/06/16 15:50:40] ppsci INFO: train_timestamps: [2.0, 2.0, 3.0, 8.0, 11.0, 11.0, 12.0, 15.0, 19.0, 21.0, 21.0, 22.0, 22.0, 23.0, 24.0, 24.0, 24.0, 25.0, 29.0, 30.0, 33.0, 36.0, 38.0, 39.0, 39.0, 40.0, 43.0, 44.0, 44.0, 49.0]
[2023/06/16 15:50:40] ppsci INFO: val_timestamps: [1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34.0, 35.0, 36.0, 37.0, 38.0, 39.0, 40.0, 41.0, 42.0, 43.0, 44.0, 45.0, 46.0, 47.0, 48.0, 49.0, 50.0]
[2023/06/16 15:50:41] ppsci INFO: Using paddlepaddle develop(3261b10) on device Place(gpu:0)
[2023/06/16 15:50:41] ppsci INFO: Set to_static=False for forward computation.
Traceback (most recent call last):
  File "E:\AI\AI for science\ppsci_test\examples\cylinder\2d_unsteady\cylinder2d_unsteady_Re100.py", line 231, in <module>
    solver.train()
  File "D:\anaconda3\envs\ppsci\lib\site-packages\ppsci\solver\solver.py", line 377, in train
    self.train_epoch_func(self, epoch_id, self.log_freq)
  File "D:\anaconda3\envs\ppsci\lib\site-packages\ppsci\solver\train.py", line 72, in train_epoch_func
    constraint_losses = solver.forward_helper.train_forward(
  File "D:\anaconda3\envs\ppsci\lib\site-packages\paddle\jit\dy2static\program_translator.py", line 459, in __call__
    return self._call_dygraph_function(*args, **kwargs)
  File "D:\anaconda3\envs\ppsci\lib\site-packages\paddle\jit\dy2static\program_translator.py", line 529, in _call_dygraph_function
    return self.dygraph_function(*args, **kwargs)
  File "D:\anaconda3\envs\ppsci\lib\site-packages\ppsci\utils\expression.py", line 85, in train_forward
    output_dict[name] = expr({**output_dict, **input_dicts[i]})
  File "D:\anaconda3\envs\ppsci\lib\site-packages\ppsci\equation\pde\navier_stokes.py", line 65, in momentum_x_compute_func
    momentum_x += jacobian(u, t)
  File "D:\anaconda3\envs\ppsci\lib\site-packages\ppsci\autodiff\ad.py", line 96, in __call__
    return self.Js[key](i, j)
  File "D:\anaconda3\envs\ppsci\lib\site-packages\ppsci\autodiff\ad.py", line 56, in __call__
    self.J[i] = paddle.grad(y, self.xs, create_graph=True)[0]
  File "D:\anaconda3\envs\ppsci\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\anaconda3\envs\ppsci\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\anaconda3\envs\ppsci\lib\site-packages\paddle\fluid\framework.py", line 462, in __impl__
    return func(*args, **kwargs)
  File "D:\anaconda3\envs\ppsci\lib\site-packages\paddle\fluid\dygraph\base.py", line 813, in grad
    return core.eager.run_partial_grad(
MemoryError:

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 53.901855MB memory on GPU 0, 7.999878GB memory has been allocated and available memory is only 0.000000B.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.
 (at ..\paddle\fluid\memory\allocation\cuda_allocator.cc:86)
```
目前试过把`residual_validator`处的`batch_size`改小，但不起作用。
能否告诉一下gpu是什么型号的，内存需要多少，这是我的gpu信息:
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.30                 Driver Version: 531.30       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1080       WDDM | 00000000:01:00.0 Off |                  N/A |
| 38%   53C    P0               50W / 180W|      3MiB /  8192MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

**Comment by HydrogenSulfate** [comment]
1. 看报错信息是训练的时候显存已经不够了，你改 residual_validator 里 batchsize大小是没有用的，因为这个对象是评估的时候用，跟训练无关。
2. 用 AIStudio 上跑了下，大约需要 14 G显存，你一定要跑的话，可以在 `Solver` 实例化的时候，加两个参数 

    ``` py
    soler = Solver(..., use_amp=True, amp_level="O1", ...)
    ```
