### ISSUE TITLE
部分算子无法计算高阶梯度？

### ISSUE THREAD

**Issue by tianshao1992** [PaddlePaddle/PaddleScience#56]
由于需要使用paddle高阶梯度的计算，但是直接采用grad不行，代码如下：

import paddle
from paddle.autograd import jacobian, hessian
from paddle.fluid.dygraph import grad

x = paddle.ones(shape=[1], dtype='float32') * 2 * np.pi
x.stop_gradient = False

y = paddle.sin(x)
dydx = grad(y, x, create_graph=True, retain_graph=True)[0]
print(dydx)
dy2dx2 = grad(dydx, x, create_graph=True, retain_graph=True)[0]
print(dy2dx2)

报错如下：

Traceback (most recent call last):
  File "F:\pycharm\Physics-AI\PINN_InverseDesign_paddle\run_paddle_grad.py", line 13, in <module>
    dydx = grad(y, x, create_graph=True, retain_graph=True)[0]
  File "<decorator-gen-49>", line 2, in grad
  File "D:\Programs\Anaconda\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\Programs\Anaconda\lib\site-packages\paddle\fluid\framework.py", line 434, in __impl__
    return func(*args, **kwargs)
  File "D:\Programs\Anaconda\lib\site-packages\paddle\fluid\dygraph\base.py", line 661, in grad
    return core.dygraph_partial_grad(
RuntimeError: (NotFound) The Op sin_grad doesn't have any grad op. If you don't intend calculating higher order derivatives, please set `create_graph` to False.
  [Hint: double_grad_node should not be null.] (at ..\paddle\fluid\imperative\partial_grad_engine.cc:923)

**Comment by tianshao1992** [comment]
采用的另一个方法是，利用backward()计算所有节点的梯度，然后再返回部分节点的梯度，请问这样做是不是效率会变低，存储量变大？

**Comment by xingfeng01** [comment]
您好，目前支持高阶微分的算子有限，sin 还没有支持。

**Comment by tianshao1992** [comment]
sin cos exp 这几个能不能提供下支持

**Comment by levi131** [comment]
感谢建议，我们会把这些算子的高阶微分支持提上日程，欢迎关注进展

**Comment by HydrogenSulfate** [comment]
你好，PaddleScience 1.0 正式版已经发布，提供了全新设计的 API 供开发使用，可以参考用户文档进行开发
https://paddlescience-docs.readthedocs.io/zh/latest/
